"""Initial persistence schema

Revision ID: 0001
Revises: 
Create Date: 2026-05-30 18:31:18.631814
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('original_query', sa.String(length=4000), nullable=False),
    sa.Column('original_input', sa.JSON(), nullable=False),
    sa.Column('current_brief', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.Column('updated_at', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_shopping_sessions'))
    )
    op.create_table('shopping_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.Column('started_at', sa.String(length=35), nullable=True),
    sa.Column('completed_at', sa.String(length=35), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['shopping_sessions.session_id'], name=op.f('fk_shopping_runs_session_id_shopping_sessions')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_shopping_runs'))
    )
    op.create_index('ix_shopping_runs_session_id', 'shopping_runs', ['session_id'], unique=False)
    op.create_table('agent_run_records',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('agent_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.String(length=35), nullable=False),
    sa.Column('ended_at', sa.String(length=35), nullable=True),
    sa.Column('trace_id', sa.String(length=300), nullable=True),
    sa.Column('record', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_agent_run_records_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_agent_run_records'))
    )
    op.create_index('ix_agent_run_records_agent_name', 'agent_run_records', ['agent_name'], unique=False)
    op.create_index('ix_agent_run_records_run_id', 'agent_run_records', ['run_id'], unique=False)
    op.create_index('ix_agent_run_records_stage', 'agent_run_records', ['stage'], unique=False)
    op.create_index('ix_agent_run_records_trace_id', 'agent_run_records', ['trace_id'], unique=False)
    op.create_table('canonical_products',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('product', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_canonical_products_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_canonical_products'))
    )
    op.create_index('ix_canonical_products_brand_model', 'canonical_products', ['brand', 'model'], unique=False)
    op.create_index('ix_canonical_products_category', 'canonical_products', ['category'], unique=False)
    op.create_index('ix_canonical_products_model', 'canonical_products', ['model'], unique=False)
    op.create_index('ix_canonical_products_name', 'canonical_products', ['name'], unique=False)
    op.create_index('ix_canonical_products_run_id', 'canonical_products', ['run_id'], unique=False)
    op.create_table('comparison_matrices',
    sa.Column('matrix_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('matrix', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_comparison_matrices_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('matrix_id', name=op.f('pk_comparison_matrices'))
    )
    op.create_index('ix_comparison_matrices_run_id', 'comparison_matrices', ['run_id'], unique=False)
    op.create_table('run_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('occurred_at', sa.String(length=35), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_run_events_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_run_events')),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_run_events_run_id_sequence')
    )
    op.create_index('ix_run_events_run_id', 'run_events', ['run_id'], unique=False)
    op.create_index('ix_run_events_run_id_sequence', 'run_events', ['run_id', 'sequence'], unique=False)
    op.create_table('refinement_requests',
    sa.Column('refinement_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('instruction', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.Column('refinement', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_refinement_requests_run_id_shopping_runs')),
    sa.ForeignKeyConstraint(['session_id'], ['shopping_sessions.session_id'], name=op.f('fk_refinement_requests_session_id_shopping_sessions')),
    sa.PrimaryKeyConstraint('refinement_id', name=op.f('pk_refinement_requests'))
    )
    op.create_index('ix_refinement_requests_run_id', 'refinement_requests', ['run_id'], unique=False)
    op.create_index('ix_refinement_requests_session_id', 'refinement_requests', ['session_id'], unique=False)
    op.create_table('search_plans',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_search_plans_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_search_plans'))
    )
    op.create_index('ix_search_plans_run_id', 'search_plans', ['run_id'], unique=False)
    op.create_table('video_review_evidence_bundles',
    sa.Column('bundle_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('bundle', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_video_review_evidence_bundles_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('bundle_id', name=op.f('pk_video_review_evidence_bundles'))
    )
    op.create_index('ix_video_review_evidence_bundles_run_id', 'video_review_evidence_bundles', ['run_id'], unique=False)
    op.create_table('video_transcript_segments',
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=128), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(length=40), nullable=False),
    sa.Column('text', sa.String(length=5000), nullable=True),
    sa.Column('gap_reason', sa.String(length=500), nullable=True),
    sa.Column('segment', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_video_transcript_segments_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('segment_id', name=op.f('pk_video_transcript_segments'))
    )
    op.create_index('ix_video_transcript_segments_run_id', 'video_transcript_segments', ['run_id'], unique=False)
    op.create_index('ix_video_transcript_segments_video_id', 'video_transcript_segments', ['video_id'], unique=False)
    op.create_table('category_analyses',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['canonical_products.product_id'], name=op.f('fk_category_analyses_product_id_canonical_products')),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_category_analyses_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('analysis_id', name=op.f('pk_category_analyses'))
    )
    op.create_index('ix_category_analyses_category', 'category_analyses', ['category'], unique=False)
    op.create_index('ix_category_analyses_product_id', 'category_analyses', ['product_id'], unique=False)
    op.create_index('ix_category_analyses_run_id', 'category_analyses', ['run_id'], unique=False)
    op.create_table('product_listings',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('seller_name', sa.String(length=200), nullable=False),
    sa.Column('seller_trust_signal', sa.String(length=40), nullable=False),
    sa.Column('captured_at', sa.String(length=35), nullable=False),
    sa.Column('listing', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['canonical_products.product_id'], name=op.f('fk_product_listings_product_id_canonical_products')),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_product_listings_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('listing_id', name=op.f('pk_product_listings'))
    )
    op.create_index('ix_product_listings_product_id', 'product_listings', ['product_id'], unique=False)
    op.create_index('ix_product_listings_run_id', 'product_listings', ['run_id'], unique=False)
    op.create_index('ix_product_listings_seller_name', 'product_listings', ['seller_name'], unique=False)
    op.create_index('ix_product_listings_url', 'product_listings', ['url'], unique=False)
    op.create_table('search_results',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=False),
    sa.Column('provider_result_id', sa.String(length=300), nullable=True),
    sa.Column('provider_query_id', sa.String(length=300), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['search_plans.plan_id'], name=op.f('fk_search_results_plan_id_search_plans')),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_search_results_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_search_results'))
    )
    op.create_index('ix_search_results_plan_id', 'search_results', ['plan_id'], unique=False)
    op.create_index('ix_search_results_provider_name', 'search_results', ['provider_name'], unique=False)
    op.create_index('ix_search_results_provider_query_id', 'search_results', ['provider_name', 'provider_query_id'], unique=False)
    op.create_index('ix_search_results_provider_result_id', 'search_results', ['provider_name', 'provider_result_id'], unique=False)
    op.create_index('ix_search_results_run_id', 'search_results', ['run_id'], unique=False)
    op.create_index('ix_search_results_url', 'search_results', ['url'], unique=False)
    op.create_table('candidate_shortlist_memberships',
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['product_listings.listing_id'], name=op.f('fk_candidate_shortlist_memberships_listing_id_product_listings')),
    sa.ForeignKeyConstraint(['product_id'], ['canonical_products.product_id'], name=op.f('fk_candidate_shortlist_memberships_product_id_canonical_products')),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_candidate_shortlist_memberships_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('membership_id', name=op.f('pk_candidate_shortlist_memberships')),
    sa.UniqueConstraint('run_id', 'candidate_id', name='uq_candidate_shortlist_memberships_run_id_candidate_id')
    )
    op.create_index('ix_candidate_shortlist_memberships_listing_id', 'candidate_shortlist_memberships', ['listing_id'], unique=False)
    op.create_index('ix_candidate_shortlist_memberships_product_id', 'candidate_shortlist_memberships', ['product_id'], unique=False)
    op.create_index('ix_candidate_shortlist_memberships_run_id', 'candidate_shortlist_memberships', ['run_id'], unique=False)
    op.create_table('listing_trust_assessments',
    sa.Column('trust_assessment_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('assessed_at', sa.String(length=35), nullable=False),
    sa.Column('assessment', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['product_listings.listing_id'], name=op.f('fk_listing_trust_assessments_listing_id_product_listings')),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_listing_trust_assessments_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('trust_assessment_id', name=op.f('pk_listing_trust_assessments'))
    )
    op.create_index('ix_listing_trust_assessments_listing_id', 'listing_trust_assessments', ['listing_id'], unique=False)
    op.create_index('ix_listing_trust_assessments_run_id', 'listing_trust_assessments', ['run_id'], unique=False)
    op.create_table('recommendation_bundles',
    sa.Column('bundle_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('comparison_matrix_id', sa.String(length=36), nullable=False),
    sa.Column('final_product_id', sa.String(length=36), nullable=True),
    sa.Column('final_listing_id', sa.String(length=36), nullable=True),
    sa.Column('no_strong_buy', sa.Boolean(), nullable=False),
    sa.Column('bundle', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_matrix_id'], ['comparison_matrices.matrix_id'], name=op.f('fk_recommendation_bundles_comparison_matrix_id_comparison_matrices')),
    sa.ForeignKeyConstraint(['final_listing_id'], ['product_listings.listing_id'], name=op.f('fk_recommendation_bundles_final_listing_id_product_listings')),
    sa.ForeignKeyConstraint(['final_product_id'], ['canonical_products.product_id'], name=op.f('fk_recommendation_bundles_final_product_id_canonical_products')),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_recommendation_bundles_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('bundle_id', name=op.f('pk_recommendation_bundles'))
    )
    op.create_index('ix_recommendation_bundles_final_listing_id', 'recommendation_bundles', ['final_listing_id'], unique=False)
    op.create_index('ix_recommendation_bundles_final_product_id', 'recommendation_bundles', ['final_product_id'], unique=False)
    op.create_index('ix_recommendation_bundles_run_id', 'recommendation_bundles', ['run_id'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('search_result_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=False),
    sa.Column('provider_result_id', sa.String(length=300), nullable=True),
    sa.Column('provider_query_id', sa.String(length=300), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_source_snapshots_run_id_shopping_runs')),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.source_id'], name=op.f('fk_source_snapshots_search_result_id_search_results')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_source_snapshots'))
    )
    op.create_index('ix_source_snapshots_provider_name', 'source_snapshots', ['provider_name'], unique=False)
    op.create_index('ix_source_snapshots_provider_query_id', 'source_snapshots', ['provider_name', 'provider_query_id'], unique=False)
    op.create_index('ix_source_snapshots_provider_result_id', 'source_snapshots', ['provider_name', 'provider_result_id'], unique=False)
    op.create_index('ix_source_snapshots_run_id', 'source_snapshots', ['run_id'], unique=False)
    op.create_index('ix_source_snapshots_search_result_id', 'source_snapshots', ['search_result_id'], unique=False)
    op.create_index('ix_source_snapshots_url', 'source_snapshots', ['url'], unique=False)
    op.create_table('user_added_products',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('input_text', sa.String(length=1000), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.Column('user_added', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['product_listings.listing_id'], name=op.f('fk_user_added_products_listing_id_product_listings')),
    sa.ForeignKeyConstraint(['product_id'], ['canonical_products.product_id'], name=op.f('fk_user_added_products_product_id_canonical_products')),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_user_added_products_run_id_shopping_runs')),
    sa.ForeignKeyConstraint(['session_id'], ['shopping_sessions.session_id'], name=op.f('fk_user_added_products_session_id_shopping_sessions')),
    sa.PrimaryKeyConstraint('candidate_id', name=op.f('pk_user_added_products'))
    )
    op.create_index('ix_user_added_products_listing_id', 'user_added_products', ['listing_id'], unique=False)
    op.create_index('ix_user_added_products_product_id', 'user_added_products', ['product_id'], unique=False)
    op.create_index('ix_user_added_products_run_id', 'user_added_products', ['run_id'], unique=False)
    op.create_index('ix_user_added_products_session_id', 'user_added_products', ['session_id'], unique=False)
    op.create_index('ix_user_added_products_url', 'user_added_products', ['url'], unique=False)
    op.create_table('result_versions',
    sa.Column('result_version_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('recommendation_bundle_id', sa.String(length=36), nullable=False),
    sa.Column('comparison_matrix_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['comparison_matrix_id'], ['comparison_matrices.matrix_id'], name=op.f('fk_result_versions_comparison_matrix_id_comparison_matrices')),
    sa.ForeignKeyConstraint(['recommendation_bundle_id'], ['recommendation_bundles.bundle_id'], name=op.f('fk_result_versions_recommendation_bundle_id_recommendation_bundles')),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_result_versions_run_id_shopping_runs')),
    sa.PrimaryKeyConstraint('result_version_id', name=op.f('pk_result_versions')),
    sa.UniqueConstraint('run_id', 'version', name='uq_result_versions_run_id_version')
    )
    op.create_index('ix_result_versions_run_id', 'result_versions', ['run_id'], unique=False)
    op.create_index('ix_result_versions_run_id_version', 'result_versions', ['run_id', 'version'], unique=False)
    op.create_table('source_evidence',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_source_evidence_run_id_shopping_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['source_snapshots.source_id'], name=op.f('fk_source_evidence_source_id_source_snapshots')),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_source_evidence'))
    )
    op.create_index('ix_source_evidence_run_id', 'source_evidence', ['run_id'], unique=False)
    op.create_index('ix_source_evidence_source_id', 'source_evidence', ['source_id'], unique=False)
    op.create_table('video_review_evidence',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('bundle_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('source_target_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_claim_id', sa.String(length=120), nullable=True),
    sa.Column('metadata_only', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['video_review_evidence_bundles.bundle_id'], name=op.f('fk_video_review_evidence_bundle_id_video_review_evidence_bundles')),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_video_review_evidence_run_id_shopping_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['source_snapshots.source_id'], name=op.f('fk_video_review_evidence_source_id_source_snapshots')),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_video_review_evidence'))
    )
    op.create_index('ix_video_review_evidence_bundle_id', 'video_review_evidence', ['bundle_id'], unique=False)
    op.create_index('ix_video_review_evidence_candidate_id', 'video_review_evidence', ['candidate_id'], unique=False)
    op.create_index('ix_video_review_evidence_listing_id', 'video_review_evidence', ['listing_id'], unique=False)
    op.create_index('ix_video_review_evidence_product_id', 'video_review_evidence', ['product_id'], unique=False)
    op.create_index('ix_video_review_evidence_recommendation_claim_id', 'video_review_evidence', ['recommendation_claim_id'], unique=False)
    op.create_index('ix_video_review_evidence_run_id', 'video_review_evidence', ['run_id'], unique=False)
    op.create_index('ix_video_review_evidence_source_id', 'video_review_evidence', ['source_id'], unique=False)
    op.create_index('ix_video_review_evidence_video_id', 'video_review_evidence', ['video_id'], unique=False)
    op.create_table('video_sources',
    sa.Column('video_record_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('channel_id', sa.String(length=128), nullable=True),
    sa.Column('channel_name', sa.String(length=200), nullable=True),
    sa.Column('transcript_availability', sa.String(length=40), nullable=False),
    sa.Column('channel_metadata', sa.JSON(), nullable=False),
    sa.Column('video', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['shopping_runs.run_id'], name=op.f('fk_video_sources_run_id_shopping_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['source_snapshots.source_id'], name=op.f('fk_video_sources_source_id_source_snapshots')),
    sa.PrimaryKeyConstraint('video_record_id', name=op.f('pk_video_sources'))
    )
    op.create_index('ix_video_sources_channel_id', 'video_sources', ['channel_id'], unique=False)
    op.create_index('ix_video_sources_run_id', 'video_sources', ['run_id'], unique=False)
    op.create_index('ix_video_sources_source_id', 'video_sources', ['source_id'], unique=False)
    op.create_index('ix_video_sources_video_id', 'video_sources', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_sources_video_id', table_name='video_sources')
    op.drop_index('ix_video_sources_source_id', table_name='video_sources')
    op.drop_index('ix_video_sources_run_id', table_name='video_sources')
    op.drop_index('ix_video_sources_channel_id', table_name='video_sources')
    op.drop_table('video_sources')
    op.drop_index('ix_video_review_evidence_video_id', table_name='video_review_evidence')
    op.drop_index('ix_video_review_evidence_source_id', table_name='video_review_evidence')
    op.drop_index('ix_video_review_evidence_run_id', table_name='video_review_evidence')
    op.drop_index('ix_video_review_evidence_recommendation_claim_id', table_name='video_review_evidence')
    op.drop_index('ix_video_review_evidence_product_id', table_name='video_review_evidence')
    op.drop_index('ix_video_review_evidence_listing_id', table_name='video_review_evidence')
    op.drop_index('ix_video_review_evidence_candidate_id', table_name='video_review_evidence')
    op.drop_index('ix_video_review_evidence_bundle_id', table_name='video_review_evidence')
    op.drop_table('video_review_evidence')
    op.drop_index('ix_source_evidence_source_id', table_name='source_evidence')
    op.drop_index('ix_source_evidence_run_id', table_name='source_evidence')
    op.drop_table('source_evidence')
    op.drop_index('ix_result_versions_run_id_version', table_name='result_versions')
    op.drop_index('ix_result_versions_run_id', table_name='result_versions')
    op.drop_table('result_versions')
    op.drop_index('ix_user_added_products_url', table_name='user_added_products')
    op.drop_index('ix_user_added_products_session_id', table_name='user_added_products')
    op.drop_index('ix_user_added_products_run_id', table_name='user_added_products')
    op.drop_index('ix_user_added_products_product_id', table_name='user_added_products')
    op.drop_index('ix_user_added_products_listing_id', table_name='user_added_products')
    op.drop_table('user_added_products')
    op.drop_index('ix_source_snapshots_url', table_name='source_snapshots')
    op.drop_index('ix_source_snapshots_search_result_id', table_name='source_snapshots')
    op.drop_index('ix_source_snapshots_run_id', table_name='source_snapshots')
    op.drop_index('ix_source_snapshots_provider_result_id', table_name='source_snapshots')
    op.drop_index('ix_source_snapshots_provider_query_id', table_name='source_snapshots')
    op.drop_index('ix_source_snapshots_provider_name', table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index('ix_recommendation_bundles_run_id', table_name='recommendation_bundles')
    op.drop_index('ix_recommendation_bundles_final_product_id', table_name='recommendation_bundles')
    op.drop_index('ix_recommendation_bundles_final_listing_id', table_name='recommendation_bundles')
    op.drop_table('recommendation_bundles')
    op.drop_index('ix_listing_trust_assessments_run_id', table_name='listing_trust_assessments')
    op.drop_index('ix_listing_trust_assessments_listing_id', table_name='listing_trust_assessments')
    op.drop_table('listing_trust_assessments')
    op.drop_index('ix_candidate_shortlist_memberships_run_id', table_name='candidate_shortlist_memberships')
    op.drop_index('ix_candidate_shortlist_memberships_product_id', table_name='candidate_shortlist_memberships')
    op.drop_index('ix_candidate_shortlist_memberships_listing_id', table_name='candidate_shortlist_memberships')
    op.drop_table('candidate_shortlist_memberships')
    op.drop_index('ix_search_results_url', table_name='search_results')
    op.drop_index('ix_search_results_run_id', table_name='search_results')
    op.drop_index('ix_search_results_provider_result_id', table_name='search_results')
    op.drop_index('ix_search_results_provider_query_id', table_name='search_results')
    op.drop_index('ix_search_results_provider_name', table_name='search_results')
    op.drop_index('ix_search_results_plan_id', table_name='search_results')
    op.drop_table('search_results')
    op.drop_index('ix_product_listings_url', table_name='product_listings')
    op.drop_index('ix_product_listings_seller_name', table_name='product_listings')
    op.drop_index('ix_product_listings_run_id', table_name='product_listings')
    op.drop_index('ix_product_listings_product_id', table_name='product_listings')
    op.drop_table('product_listings')
    op.drop_index('ix_category_analyses_run_id', table_name='category_analyses')
    op.drop_index('ix_category_analyses_product_id', table_name='category_analyses')
    op.drop_index('ix_category_analyses_category', table_name='category_analyses')
    op.drop_table('category_analyses')
    op.drop_index('ix_video_transcript_segments_video_id', table_name='video_transcript_segments')
    op.drop_index('ix_video_transcript_segments_run_id', table_name='video_transcript_segments')
    op.drop_table('video_transcript_segments')
    op.drop_index('ix_video_review_evidence_bundles_run_id', table_name='video_review_evidence_bundles')
    op.drop_table('video_review_evidence_bundles')
    op.drop_index('ix_search_plans_run_id', table_name='search_plans')
    op.drop_table('search_plans')
    op.drop_index('ix_run_events_run_id_sequence', table_name='run_events')
    op.drop_index('ix_run_events_run_id', table_name='run_events')
    op.drop_table('run_events')
    op.drop_index('ix_refinement_requests_session_id', table_name='refinement_requests')
    op.drop_index('ix_refinement_requests_run_id', table_name='refinement_requests')
    op.drop_table('refinement_requests')
    op.drop_index('ix_comparison_matrices_run_id', table_name='comparison_matrices')
    op.drop_table('comparison_matrices')
    op.drop_index('ix_canonical_products_run_id', table_name='canonical_products')
    op.drop_index('ix_canonical_products_name', table_name='canonical_products')
    op.drop_index('ix_canonical_products_model', table_name='canonical_products')
    op.drop_index('ix_canonical_products_category', table_name='canonical_products')
    op.drop_index('ix_canonical_products_brand_model', table_name='canonical_products')
    op.drop_table('canonical_products')
    op.drop_index('ix_agent_run_records_trace_id', table_name='agent_run_records')
    op.drop_index('ix_agent_run_records_stage', table_name='agent_run_records')
    op.drop_index('ix_agent_run_records_run_id', table_name='agent_run_records')
    op.drop_index('ix_agent_run_records_agent_name', table_name='agent_run_records')
    op.drop_table('agent_run_records')
    op.drop_index('ix_shopping_runs_session_id', table_name='shopping_runs')
    op.drop_table('shopping_runs')
    op.drop_table('shopping_sessions')
    # ### end Alembic commands ###
